services:
  spring-security-demo:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: spring-security-demo
    container_name: spring-security-demo
    image: javawiki/spring-security-demo:1.0.0
    ports:
      - "18000:18000"
    restart: "always"
    healthcheck:
      test: "curl -f http://localhost:18000/actuator/health || exit 1"
      start_period: 60s
      interval: 30s
      timeout: 60s
      retries: 6
    environment:
      TZ: Asia/Shanghai
      SERVER_PORT: 18000
      SPRING_PROFILES_ACTIVE: dev
      JAVA_OPTS: -Dinfo.tags.environment=dev
