server:
  port: 18000

spring:
  application:
    name: @project.name@

logging:
  level:
    cn:
      netbuffer: debug
    org:
      springframework:
        security:
          authentication:
            dao:
              DaoAuthenticationProvider: debug
          web:
            FilterChainProxy: debug
            access:
              intercept:
                FilterSecurityInterceptor: trace